[project]
name = "threat-intel-aggregator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "feedparser>=6.0.11",
    "gradio>=5.38.1",
    "lxml>=6.0.0",
    "ollama>=0.5.1",
]
